import random

def guess():
    """This is the function that runs the guess-the-number.py script

    :return: It has no return value
    """
    unknown = random.randrange(1, 101)
    for i in range(1,11):
        usernumber = inputnumber('Enter a number: ')
        comparenumber(unknown, usernumber)

def inputnumber(message):
    """This function verifies whether the user typed an integer as input.

    :param message: This argument is usually a prompt message
    :return: It returns an integer type.
    """
    while True:
        try:
            userNumber = int(input('Enter a number:'))
        except ValueError:
            print('This is not a whole number')
        else:
            return userNumber
            break

def comparenumber(unknownnumber, usernumber):
    """This function compares the unknown number with the userinput number.

    :param unknownnumber: This parameter is for the unknown number. It is randomly
    generated by the computer
    :param usernumber: This parameter is for the userinput. It must be an integer
    :return: It has no return value.
    """
    comparednumber = unknownnumber - usernumber
    if usernumber == unknownnumber:
        print('You are correct!')
    elif usernumber < unknownnumber:
        print('Your choice is less than the answer')
        print('Your choice is about {0} below the answer'.format(comparednumber+5))
    else:
        print('Your choice is greater than the answer')
        print('Your choice is about {0} greater than the answer' .format(5-comparednumber))


guess()
